version: '2'
services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - php7
      - db
    volumes:
      - ./app:/var/www
    ports:
      - "80:80"
  php7:
    build: ./docker/php7
    ports:
      - "9000"
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    environment: 
      XDEBUG_CONFIG: remote_host=192.168.0.101 #Подставить свой удаленный IP
      PHP_IDE_CONFIG: "serverName=docker"
      DATABASE_NAME: testing
      DATABASE_USER: root
      DATABASE_PASSWORD: root
  db:
    container_name: testing
    build: ./docker/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/postgresql/postgresql-data:/var/lib/mysql
      - ./docker/postgresql/dumps:/docker-entrypoint-initdb.d
  memcached:
      container_name: memcached
      build: ./docker/memcached
      ports:
        - "11211:11211"